---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later
kind: pipeline
name: default

steps:
  # Clone submodules (reuse docs)
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init

  # Check for REUSE compliance
  - name: reuse
    image: fsfe/reuse:latest
    commands:
      - reuse lint

  # Create translations for markdown via PO files
  - name: po4a
    image: alpine:3.16
    commands:
      - apk add perl-yaml-tiny po4a diffutils
      - cd site && po4a po/po4a.conf

  # Create .status file for important i18n translation strings
  - name: check_translations
    image: python:3.10-alpine
    commands:
      - python3 check_translations.py site/i18n

  # Build hugo
  - name: hugo
    image: plugins/hugo
    settings:
      source: site
      hugo_version: 0.98.0
      validate: false

  # Build and deploy Docker
  - name: deploy
    image: docker/compose:1.29.2
    environment:
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
      # Use BuildKit to skip "development" step in Dockerfiles
      DOCKER_BUILDKIT: 1
    commands:
      - docker-compose -p reuse-website up --build -d
    volumes:
      - name: dockersock
        path: /run/user/1001/docker.sock
    when:
      branch:
        - main
      event:
        - push
        - tag
        - deployment

node:
  cont2: noris

volumes:
  - name: dockersock
    host:
      path: /run/user/1001/docker.sock
---
kind: signature
hmac: ff30cbb962b7805bb38886c3121b9159e1758fc9ac40577e67015771506683d8

...
