# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

pipeline:
  syntaxcheck:
    image: monachus/hugo
    commands:
        - cd site; hugo

  reuse:
    image: fsfe/reuse:latest
    commands:
      - reuse lint

  deploy:
    commands:
      # Run docker compose
      - docker-compose up --build -d
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
       branch: master
       event: [push, tag, deployment]
