---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later
kind: pipeline
name: default

steps:
  # Clone submodules (reuse docs)
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init

  # Check for REUSE compliance
  - name: reuse
    image: fsfe/reuse:latest
    commands:
      - reuse lint

  # Build and copy reuse docs files to reuse website
  - name: sync-docs
    image: alpine:3
    commands:
      - apk add bash perl-yaml-tiny po4a
      - bash sync-docs.sh

  # Create translations for markdown via PO files
  - name: po4a
    image: alpine:3
    commands:
      - apk add perl-yaml-tiny po4a
      - cd site && po4a po/po4a.conf

  # Build hugo
  - name: hugo
    image: plugins/hugo
    settings:
      source: site
      validate: true

  # Build and deploy Docker
  - name: deploy
    image: docker/compose:1.29.2
    environment:
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
    commands:
      - docker-compose -p reuse-website up --build -d
    volumes:
      - name: dockersock
        path: /run/user/1001/docker.sock
    when:
      branch:
        - master
      event:
        - push
        - tag
        - deployment

node:
  cont2: noris

volumes:
  - name: dockersock
    host:
      path: /run/user/1001/docker.sock
---
kind: signature
hmac: bfa7a2616521bf482485d2ada01d402b532ff4e838c3f2c0e7bf537df8f59e05

...
