---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later
kind: pipeline
type: docker
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote

steps:
- name: syntaxcheck
  image: monachus/hugo
  commands:
  - cd site; hugo

- name: reuse
  image: fsfe/reuse:latest
  commands:
  - reuse lint

- name: deploy
  image: tmaier/docker-compose
  commands:
  - docker-compose up --build -d
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  when:
    branch:
    - master
    event:
    - push
    - tag
    - deployment

volumes:
- name: docker-socket
  host:
    path: /var/run/docker.sock

...
