---
# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later
kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote

- name: syntaxcheck
  image: monachus/hugo
  commands:
  - cd site; hugo

- name: reuse
  image: fsfe/reuse:latest
  commands:
  - reuse lint

- name: deploy
  image: docker/compose:1.24.0
  commands:
  - docker-compose up --build -d
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  when:
    branch:
    - master
    event:
    - push
    - tag
    - deployment


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

...
