# SPDX-FileCopyrightText: Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

baseURL         = "https://reuse.software/"
languageCode    = "en"
title           = "REUSE"
theme           = "github-project-landing-page"

# TODO: Get rid of this. The reason this is here is because a translated page
# can reference an untranslated page.
refLinksErrorLevel = "warning"

[markup]
[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 1

[markup.highlight]
  codeFences = true
  style = "emacs"

#[permalinks]
#        page = "/:title/"
#        about = "/:filename/"


[params]
    subtitle = "Make licensing easy for everyone"
    description = "We make licensing easy for humans and machines alike. REUSE solves a fundamental issue that Free Software licensing has at the very source. Adopting our recommendations is as easy as one-two-three!"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"

    current_spec="spec-3.3"

[params.social]
  Github        = "search?q=topic%3Areuse+org%3Afsfe&type=Repositories"
  Git           = "https://git.fsfe.org/reuse"
  Email         = "https://lists.fsfe.org/postorius/lists/reuse.lists.fsfe.org/"
  Twitter       = "fsfe"
  Stackoverflow = ""
  Mastodon      = "mastodon.social/@fsfe"
  Diaspora      = ""

# Languages
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[languages]
[languages.en]
  weight = 1
  languageName = "English"
  contentDir = "content/en"
[languages.cs]
  languageName = "Česky"
  contentDir = "content/cs"
[languages.de]
  languageName = "Deutsch"
  contentDir = "content/de"
[languages.fr]
  languageName = "Français"
  contentDir = "content/fr"
[languages.uk]
  languageName = "Українська"
  contentDir = "content/uk"


[menu]
[[menu.main]]
  identifier = "tutorial"
  weight = 100
  url = "/tutorial/"
[[menu.main]]
  identifier = "faq"
  weight = 200
  url = "/faq/"
[[menu.main]]
  identifier = "dev"
  weight = 300
  url = "/dev/"
[[menu.main]]
  identifier = "spec"
  weight = 300
  url = "/spec/"
[[menu.main]]
  identifier = "resources"
  weight = 500
  url = "/resources/"
[[menu.main]]
  identifier = "supporters"
  weight = 900
  url = "/supporters/"
[[menu.main]]
  identifier = "api"
  weight = 1000
  url = "https://api.reuse.software"
