# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Run Tests

on: [push, pull_request]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1

  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Hugo build
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Build
      run: hugo --minify

    - name: Build Dockerfile
      run: |
        docker build -t reuse-web .
